# Generated by Django 5.0.3 on 2024-06-13 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('number', models.IntegerField()),
                ('secondary_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_type', to='pokeapp.type')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_type', to='pokeapp.type')),
            ],
        ),
    ]
